import { useState } from "react";
import Head from "next/head";

const mapboxgl = require("mapbox-gl/dist/mapbox-gl.js");
mapboxgl.accessToken =
  "pk.eyJ1IjoiZGF5c2hhd24yMSIsImEiOiJja3Nqczgydm8wMGR0Mm9uMGZra3dsdWQ4In0.SRJo_b_HZGiN3EtvqSA4aw";

export default function Map() {
  const [pageIsMounted, setPageIsMounted] = useState(false);
  const [lng, setLng] = useState(-95.35);
  const [lat, setLat] = useState(29.74);
  const [zoom, setZoom] = useState(10);
  useEffect(() => {
    setPageIsMounted(true);
    const map = new mapboxgl.Map({
      container: "my-map",
      style: "mapbox://styles/mapbox/streets-v11",
      center: [lng, lat],
      zoom: zoom,
    });
    map.addControl(new mapboxgl.NavigationControl(), "top-right");

    map.on("move", () => {
      setLng(map.getCenter().lng.toFixed(4));
      setLat(map.getCenter().lat.toFixed(4));
      setZoom(map.getZoom().toFixed(2));
    });

    // Clean up on unmount
    return () => map.remove();
  }, []);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://api.mapbox.com/mapbox-gl-js/v2.3.1/mapbox-gl.css"
          rel="stylesheet"
        />
      </Head>
      <div id="my-map" style={{ height: 500, width: 500 }} />
    </div>
  );
}
